_schema-version: "3.3"
ID: empsaldetails
version: 1.0.0

modules:
  - name: employee-sal-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 512M
      disk-quota: 512M
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    requires:
      - name: employee-sal-db
      - name: empsaldetails-auth

  - name: employee-sal-db-deployer
    type: hdb
    path: gen/db
    requires:
      - name: employee-sal-db

  - name: empsaldetails
    type: approuter.nodejs
    path: app/router
    parameters:
      keep-existing-routes: true
      memory: 256M
      disk-quota: 256M
    requires:
      - name: srv-api
        group: destinations
        properties:
          name: srv-api
          url: ~{srv-url}
          forwardAuthToken: true
      - name: empsaldetails-auth
    provides:
      - name: app-api
        properties:
          app-protocol: ${protocol}
          app-uri: ${default-uri}

resources:
  - name: employee-sal-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana
      service-plan: hdi-shared

  - name: empsaldetails-auth
    type: org.cloudfoundry.managed-service
    parameters:
      service: xsuaa
      service-plan: application
      path: ./xs-security.json
      config:
        xsappname: empsaldetails-${org}-${space}
        tenant-mode: dedicated
        oauth2-configuration:
          credential-types:
            - binding-secret
            - x509
          redirect-uris:
            - https://*~{app-api/app-uri}/**
    requires:
      - name: app-api

description: "A simple CAP project."

parameters:
  enable-parallel-deployments: true

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm ci
        - npx cds build --production
